#!/usr/bin/env bash
# bash script that displays numbers from 1 to 100 adding the fizz buzz tricks
# if multiple 5 then buzz
# if multiple 3 the fizz

for (( s=1; s<=100; s++))
do
    if (( s % 3 == 0 && s % 5 == 0))
    then
	echo "FizzBuzz"
    elif (( s % 3 == 0 ))
    then
	echo "Fizz"
    elif (( s % 5 == 0))
    then
       	echo "Buzz"
    else
	echo "$s"
    fi
done
