#!/usr/bin/env bash
# Print x8 Best School using While Loop
# but for the 4th iteration, displays bad luck
# and for the 8th iteration display good luck

s=1
while [ $s -le 10 ]
do
    if [ "$s" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$s" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi

    ((s++))
done
