#!/usr/bin/env bash
# script that displays the numbers from 1 to 20:
# displays 4 and bad luck from China for the 4th loop iteration
# displays 9 and bad luck from Japan for the 9th loop iteration
# displays 17 and bad luck from Italy for the 17th loop iteration

s=1
while [ $s -le 20 ]
do

    case $s in

    4)
	echo "$s"
	echo "bad luck from China"
	;;
    9)
	echo "$s"
        echo "bad luck from Japan"
	;;
    17)
	echo "$s"
        echo "bad luck from Italy"
	;;
    *)
        echo "$s"
	;;
    esac
    ((s++))
done
