#!/usr/bin/env bash
# bash script that gives you information about the school file.

s="school"
if [ -e "$s" ]
then
    echo "$s file exists"
    if [ -s "$s" ]
    then
	echo "$s file is not empty"
    else
	echo "$s file is empty"
    fi
    if [ -f "$s" ]
    then
	echo "$s is a regular file"
    fi
else
    echo "$s file does not exist"
fi
